export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const CHECK_COOKIES="CHECK_COOKIES"
export const REMOVE_COOKIES="REMOVE_COOKIES"

export const SET_USERNAME="SET_USERNAME"
export const SET_PASSWORD="SET_PASSWORD"


export const OPEN_WEBSOCKET="OPEN_WEBSOCKET"
export const CLOSE_WEBSOCKET="CLOSE_WEBSOCKET"
export const CHECK_WEBSOCKET_EXIST="CHECK_WEBSOCKET_EXIST"
export const NOT_SUPPORT_WEBSOCKET="NOT_SUPPORT_WEBSOCKET"
export const WEBSOCKET_SUCCESS="WEBSOCKET_SUCCESS"
export const WEBSOCKET_ERR="WEBSOCKET_ERR"

export const SET_FINAL_MO="SET_FINAL_MO"
export const SET_FINAL_LAMBI="SET_FINAL_LAMBI"
export const SET_FINAL_FANCY_1_6="SET_FINAL_FANCY_1_6"
export const SET_FINAL_FANCY_1_12="SET_FINAL_FANCY_1_12"
export const SET_FINAL_FANCY_2_6="SET_FINAL_FANCY_2_6"
export const SET_FINAL_FANCY_2_12="SET_FINAL_FANCY_2_12"

export const SET_MATCH_ODDS="SET_MATCH_ODDS"
export const SET_LAMBI="SET_LAMBI"
export const SET_FANCY_1_6="SET_FANCY_1_6"
export const SET_FANCY_1_12="SET_FANCY_1_12"
export const SET_FANCY_2_6="SET_FANCY_2_6"
export const SET_FANCY_2_12="SET_FANCY_2_12"

export const SET_HOME="SET_HOME"
export const SET_AWAY="SET_AWAY"
export const SET_APP_INFO="SET_APP_INFO"
export const SET_NAME="SET_NAME"


export const INIT_SETTLE_MODAL="INIT_SETTLE_MODAL"

